version: '3.1'

networks:
  app-tier:
    driver: bridge

services:
  web:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
      - redis
    environment:
      PORT: 8080
    networks:
      - app-tier
  redis:
    image: redis:alpine
    ports:
     - 6379:6379
    networks:
     - app-tier

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - app-tier
    environment:
      MYSQL_DATABASE: storydb
      # So you don't have to use root, but you can if you like
      MYSQL_USER: root
      # You can use whatever password you like
      MYSQL_PASSWORD: password
      # Password for root access
      MYSQL_ROOT_PASSWORD: password

    ports:
      # Opens port 3306 on the container
      - 3306:3306
    # network_mode: bridge